---
- hosts: localhost
  connection: local
  sudo: false
  vars:
  vars_files:
    - ../defaults/main.yml
  tasks:
    - name: installing Debian/Ubuntu pre-reqs
      apt: name={{ item }} state=present
      with_items:
        - python-httplib2
      when: ansible_os_family == "Debian"
      
    - name: creating folder
      file: path={{ github_repo_root }}/{{ github_user }} state=directory

    - name: gathering repos
      uri: url="https://api.github.com/users/{{ github_user }}/repos?per_page={{ return_items }}"
      register: github_repos

    - name: write files
      template: src=../templates/query_git_repos.j2 dest={{ repos_file }}
